name: Poetry Publish
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Install dependencies
        run: poetry install --no-root --with dev
      - name: Run unit tests
        run: poetry run pytest -v

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Build package
        run: |
          poetry build
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
